# Config file .travis.yml

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

rvm:
  - 2.1.0

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=4.2

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

before_script:
  - cwd=$(pwd)
  - psql -c "CREATE USER openerp WITH PASSWORD 'admin';" -U postgres
  - psql -c 'create database ooor_test with owner openerp;' -U postgres
  - cd ${HOME}/odoo-${VERSION}
  - ./openerp-server --addons-path=${HOME}/odoo-${VERSION}/addons --db_user=postgres --db_user=openerp --db_password=admin --db_host=localhost &
  - cd $cwd
  - bundle install

script:
  - bundle exec rake

services:
  - postgresql

matrix:
  allow_failures:
    - env: "VERSION=8.0"
