language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq graphviz

services:
  - postgresql

before_script:
    - psql -c "CREATE USER openerp WITH PASSWORD 'admin';" -U postgres
    - psql -c 'create database ooor_test with owner openerp;' -U postgres
    - cd openerp
    - ./openerp-server --db_user=postgres --db_user=openerp --db_password=admin --db_host=localhost &
    - cd ..
    - bundle install

install:
    - ./spec/install_nightly.sh

script:
    - bundle exec rake

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - 2.1.0-preview2
  - rbx-2.2.1

env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"

notifications:
  email:
    - raphael.valyi@akretion.com
